#!/usr/bin/env python

import sys

from collision_visualizer.collision_visualizer_gui import MyPlugin
from rqt_gui.main import Main

plugin = 'collision_visualizer'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
