#!/usr/bin/env python
from microphone_monitoring.FusionMicrophone import FusionMicrophone, FusionAudioCapture
import sys

if __name__ == '__main__':
    #if len(sys.argv)> 1:
    #print ('hdgshgalghl;gh;wsahga;l')
    #else:
    main = FusionAudioCapture()
    # main = FusionMicrophone(50)
