#!/usr/bin/env python
from microphone_monitoring.FusionMicrophone import FusionMicrophone, FusionAudioCapture
import sys

if __name__ == '__main__':
    if True: #len(sys.argv)> 1:
        print ('hdgshgalghl;gh;wsahga;l')
        main = FusionAudioCapture()
    else:
        main = FusionMicrophone(50)
